/** Ops design system barrel — the only UI import pages should need. */
export { useMessage, useDialog } from './feedback'
export type { Tone, MessageApi, DialogApi, DialogOptions } from './feedback'
export type { RColumn, SelectOption } from './types'
export { default as RAlert } from './RAlert.vue'
export { default as RButton } from './RButton.vue'
export { default as RCheckbox } from './RCheckbox.vue'
export { default as REmpty } from './REmpty.vue'
export { default as RField } from './RField.vue'
export { default as RInput } from './RInput.vue'
export { default as RMetric } from './RMetric.vue'
export { default as RMetricStrip } from './RMetricStrip.vue'
export { default as RModal } from './RModal.vue'
export { default as RNumberInput } from './RNumberInput.vue'
export { default as RPageHeader } from './RPageHeader.vue'
export { default as RPanel } from './RPanel.vue'
export { default as RProgress } from './RProgress.vue'
export { default as RResult } from './RResult.vue'
export { default as RSelect } from './RSelect.vue'
export { default as RSpinner } from './RSpinner.vue'
export { default as RStatusDot } from './RStatusDot.vue'
export { default as RSwitch } from './RSwitch.vue'
export { default as RTabs } from './RTabs.vue'
export { default as RTable } from './RTable.vue'
export { default as RTag } from './RTag.vue'
