//! 安装脚本:Hub 提供,包含二进制下载与 systemd 安装。

/// `hub_base` is a validated public HTTP(S) origin.
pub fn script(hub_base: &str) -> String {
    r#"#!/bin/sh
# rooster agent installer (generated by the hub)
set -eu
umask 077
HUB='{hub_base}'
TOKEN="" NAME="$(hostname)" CA_FILE="" ALLOW_UNSIGNED=0
BIN_DIR="${ROOSTER_BIN_DIR:-/usr/local/bin}"
# 引导二进制可压到 ~1/3(37 MiB → 14 MiB),30 分钟上限等价于 ≥8 KB/s 的链路。
# 低于 FETCH_SPEED_LIMIT 连续 60s 则判死链。两者都可环境变量覆盖。
FETCH_MAX_TIME="${ROOSTER_FETCH_MAX_TIME:-1800}"
FETCH_SPEED_LIMIT="${ROOSTER_FETCH_SPEED_LIMIT:-512}"
CONF_DIR="${ROOSTER_CONF_DIR:-/etc/rooster}"
DATA_DIR="${ROOSTER_DATA_DIR:-/var/lib/rooster}"
UNIT_DIR="${ROOSTER_UNIT_DIR:-/etc/systemd/system}"
fail() { echo "error: $*" >&2; exit 1; }
while [ "$#" -gt 0 ]; do
  case "$1" in
    --hub|--token|--name|--ca-file)
      [ "$#" -ge 2 ] && [ -n "$2" ] || fail "missing value for $1"
      case "$1" in --hub) HUB="$2";; --token) TOKEN="$2";; --name) NAME="$2";; --ca-file) CA_FILE="$2";; esac
      shift 2;;
    --allow-unsigned) ALLOW_UNSIGNED=1; shift;;
    --insecure) fail "use the trusted enroll.sh with --ca-sha256, or provide --ca-file; unauthenticated downloads are refused";;
    *) fail "unknown argument: $1";;
  esac
done
[ "$(id -u)" = 0 ] || fail "run as root"
[ -n "$TOKEN" ] || fail "--token is required"
case "$NAME" in ''|*[!a-zA-Z0-9._-]*) fail "invalid node name";; esac
[ "${#NAME}" -le 64 ] || fail "node name exceeds 64 characters"
case "$HUB" in https://*) PROTO='=https';; http://localhost:*|http://127.0.0.1:*|http://\[::1\]:*) PROTO='=http';; *) fail "HTTPS is required outside loopback";; esac
case "$HUB" in *[!a-zA-Z0-9.:/\[\]_-]*) fail "invalid hub URL";; esac
HUB="${HUB%/}"
for cmd in curl openssl systemctl install; do command -v "$cmd" >/dev/null 2>&1 || fail "$cmd is required"; done
[ -z "$CA_FILE" ] || [ -f "$CA_FILE" ] || fail "CA file not found"
WS_URL="$(printf '%s' "$HUB" | sed 's|^https://|wss://|; s|^http://|ws://|')/agent/ws"
# Reinstall may replace configuration, but existing client identities cannot migrate silently.
if [ -f "$DATA_DIR/pki/agent.crt" ]; then
  [ -f "$CONF_DIR/config.yaml" ] || fail "existing PKI without config; restore its config before reinstalling"
  OLD_URL="$(sed -n 's/^[[:space:]]*url:[[:space:]]*//p' "$CONF_DIR/config.yaml" | tr -d "\"'")"
  OLD_NAME="$(sed -n 's/^[[:space:]]*node-name:[[:space:]]*//p' "$CONF_DIR/config.yaml" | tr -d "\"'")"
  [ "$OLD_URL" = "$WS_URL" ] && [ "$OLD_NAME" = "$NAME" ] || fail "existing PKI belongs to a different hub/name; back up and migrate identity explicitly"
fi
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT
trap 'exit 1' HUP INT TERM
fetch() {
  # 体积优化在 hub 侧:hub 支持时回 gzip(curl 解压后落盘才是签名原文)。
  # 不断流的死链由限速看门狗提前掉,而不是靠 max-time 切断正常慢链。
  if [ -n "$CA_FILE" ]; then
    curl -fsSL --compressed --proto "$PROTO" --proto-redir "$PROTO" --connect-timeout 10 --max-time "$FETCH_MAX_TIME" --speed-limit "$FETCH_SPEED_LIMIT" --speed-time 60 --cacert "$CA_FILE" "$@"
  else
    curl -fsSL --compressed --proto "$PROTO" --proto-redir "$PROTO" --connect-timeout 10 --max-time "$FETCH_MAX_TIME" --speed-limit "$FETCH_SPEED_LIMIT" --speed-time 60 "$@"
  fi
}
# 1) verify all downloads before touching the installed files.
ARCH="$(uname -m)"
echo "[1/3] fetching the rooster agent binary ($ARCH) from $HUB ..."
if fetch -o "$TMP_DIR/rooster.new" "$HUB/v0/downloads/rooster-$ARCH"; then
  SIGNED=1
elif fetch -o "$TMP_DIR/rooster.new" "$HUB/v0/downloads/rooster"; then
  SIGNED=0
else
  fail "hub serves no binary for $ARCH (both $HUB/v0/downloads/rooster-$ARCH and /v0/downloads/rooster failed); upload a signed release package via the panel, or rerun with --allow-unsigned on a same-arch hub"
fi
if [ "$SIGNED" = 1 ]; then
  echo "      signed release package: fetching signature and verification key"
  fetch -o "$TMP_DIR/rooster.sig" "$HUB/v0/downloads/rooster-$ARCH.sig" || fail "package has no signature"
  fetch -o "$TMP_DIR/rooster.pub" "$HUB/v0/pubkey.pem" || fail "configure upgrade-public-key in hub.yaml, restart the hub, and upload a signed release"
  echo "      verifying the ed25519 package signature ..."
  # Ed25519 large files require pkeyutl -rawin, not dgst -verify.
  openssl pkeyutl -verify -pubin -inkey "$TMP_DIR/rooster.pub" -rawin \
    -in "$TMP_DIR/rooster.new" -sigfile "$TMP_DIR/rooster.sig" >/dev/null || fail "package signature verification FAILED"
elif [ "$ALLOW_UNSIGNED" != 1 ]; then
  fail "no signed package for $ARCH, but this hub serves its own unsigned binary; add --allow-unsigned for an explicit same-arch development install, or configure upgrade-public-key in hub.yaml, restart the hub and upload a signed package"
fi
chmod 700 "$TMP_DIR/rooster.new"
"$TMP_DIR/rooster.new" --version >/dev/null 2>&1 || fail "binary is incompatible with this host"
"$TMP_DIR/rooster.new" agent upgrade-guard --help >/dev/null 2>&1 || fail "binary does not support the systemd upgrade guard"

# 2) back up overwritten artifacts; never delete node data or PKI.
echo "[2/3] installing binary, config and systemd service (existing files are backed up) ..."
mkdir -p "$BIN_DIR" "$CONF_DIR" "$DATA_DIR" "$UNIT_DIR"
BACKUP="$(mktemp -d "$CONF_DIR/install-backup.XXXXXXXX")"
for file in "$CONF_DIR/config.yaml" "$CONF_DIR/server-ca.crt" "$BIN_DIR/rooster" "$UNIT_DIR/rooster.service"; do
  [ ! -e "$file" ] || cp -p "$file" "$BACKUP/"
done
quote_yaml() { printf "'"; printf '%s' "$1" | sed "s/'/''/g"; printf "'"; }
SECRET="$(openssl rand -hex 32)"
if [ -n "$CA_FILE" ]; then
  install -m 600 "$CA_FILE" "$CONF_DIR/.server-ca.new"
  mv -f "$CONF_DIR/.server-ca.new" "$CONF_DIR/server-ca.crt"
fi
{
  printf 'local:\n  agent:\n    node-name: '; quote_yaml "$NAME"
  printf '\n    data-dir: '; quote_yaml "$DATA_DIR"
  printf '\n  management:\n    listen: 127.0.0.1:9870\n    secret-key: '; quote_yaml "$SECRET"
  printf '\n  hub:\n    url: '; quote_yaml "$WS_URL"
  printf '\n    token: '; quote_yaml "$TOKEN"
  if [ -n "$CA_FILE" ]; then printf '\n    ca: '; quote_yaml "$CONF_DIR/server-ca.crt"; fi
  printf '\n'
} > "$CONF_DIR/.config.yaml.new"
chmod 600 "$CONF_DIR/.config.yaml.new"
mv -f "$CONF_DIR/.config.yaml.new" "$CONF_DIR/config.yaml"
install -m 755 "$TMP_DIR/rooster.new" "$BIN_DIR/.rooster.new"
mv -f "$BIN_DIR/.rooster.new" "$BIN_DIR/rooster"

cat > "$TMP_DIR/rooster.service" <<EOF
[Unit]
Description=Rooster protection agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$BIN_DIR/rooster agent --config $CONF_DIR/config.yaml
Restart=always
RestartSec=3
ExecStartPre=$BIN_DIR/rooster agent upgrade-guard --data-dir $DATA_DIR

[Install]
WantedBy=multi-user.target
EOF
install -m 644 "$TMP_DIR/rooster.service" "$UNIT_DIR/rooster.service"
systemctl daemon-reload
systemctl enable rooster
systemctl restart rooster

# Kernel L3/L4 defensive floor (hardening-plan item 5). Report-only by
# default: the installer never changes sysctls. Pass ROOSTER_SYSCTL_BASELINE=1
# to persist and apply the baseline via /etc/sysctl.d/99-rooster.conf.
sysctl_get() { sysctl -n "$1" 2>/dev/null || true; }
ROOSTER_SYSCTLS='net.ipv4.tcp_syncookies=1
net.ipv4.conf.all.rp_filter=1
net.ipv4.icmp_echo_ignore_broadcasts=1
net.ipv4.icmp_ignore_bogus_error_responses=1
net.netfilter.nf_conntrack_max=262144'
if command -v sysctl >/dev/null 2>&1; then
  if [ "${ROOSTER_SYSCTL_BASELINE:-0}" = 1 ]; then
    printf '%s\n' "$ROOSTER_SYSCTLS" > /etc/sysctl.d/99-rooster.conf
    sysctl -p /etc/sysctl.d/99-rooster.conf >/dev/null 2>&1 || \
      echo "warning: kernel does not expose some conntrack sysctls; see /etc/sysctl.d/99-rooster.conf"
    echo "sysctl baseline written to /etc/sysctl.d/99-rooster.conf and applied"
  else
    printf '%s\n' "$ROOSTER_SYSCTLS" | while IFS='=' read -r k want; do
      cur="$(sysctl_get "$k")"
      [ -z "$cur" ] && continue
      [ "$cur" = "$want" ] || echo "note: sysctl $k=$cur (baseline recommends $want); opt in with ROOSTER_SYSCTL_BASELINE=1"
    done
  fi
fi

# A live local API alone does not prove registration or the control channel is ready.
echo "[3/3] starting rooster and waiting for the hub connection (up to 60s) ..."
i=0
while [ "$i" -lt 60 ]; do
  printf '.'
  if systemctl is-active --quiet rooster && \
    [ "$(curl -fsS --noproxy '*' --connect-timeout 1 --max-time 2 -H "Authorization: Bearer $SECRET" http://127.0.0.1:9870/v0/management/readyz 2>/dev/null || true)" = ok ]; then
    echo ''
    echo "rooster agent installed and connected (node-name: $NAME); overwritten files backed up in $BACKUP"
    exit 0
  fi
  i=$((i + 1))
  sleep 1
done
echo ''
fail "agent did not connect to the hub; inspect journalctl -u rooster -n 50; backups: $BACKUP"
"#
    .replace("{hub_base}", &hub_base.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    #[test]
    fn generated_script_is_valid_posix_sh() {
        use std::io::Write;
        use std::process::{Command, Stdio};
        let mut child = Command::new("sh").arg("-n").stdin(Stdio::piped()).spawn().unwrap();
        child.stdin.take().unwrap().write_all(super::script("https://hub.example:9443").as_bytes()).unwrap();
        assert!(child.wait().unwrap().success());
    }

    #[test]
    fn script_enforces_verified_downloads_and_readiness() {
        let s = super::script("https://hub.example:9443");
        assert!(s.contains("--cacert"));
        assert!(!s.contains("curl -fsSLk"));
        assert!(s.contains("openssl pkeyutl -verify -pubin") && s.contains("-rawin"));
        assert!(s.contains("[ \"$ALLOW_UNSIGNED\" != 1 ]"));
        assert!(s.contains("systemctl restart rooster"));
        assert!(s.contains("/v0/management/readyz"));
    }

    /// 二进制下载走 gzip + 看门狗超时:签掉旧的硬 120s 上限就会重新引入 curl(28)。
    #[test]
    fn binary_fetch_is_encoding_negotiated_and_stall_guarded() {
        let s = super::script("https://hub.example:9443");
        assert!(s.contains("--compressed"), "fetch must accept hub-side gzip");
        assert!(!s.contains("--max-time 120"), "hard 120s cap cut slow links");
        assert!(s.contains("--speed-limit \"$FETCH_SPEED_LIMIT\""));
        assert!(s.contains("ROOSTER_FETCH_MAX_TIME:-1800"));
        // 两个变量必须在 fetch() 之前定义,且两处 curl 分支都带上。
        let fetch = s.find("fetch() {").unwrap();
        assert!(s.find("FETCH_MAX_TIME=").unwrap() < fetch);
        assert_eq!(s.matches("--compressed").count(), 2);
        assert_eq!(s.matches("--speed-time 60").count(), 2);
    }

    #[test]
    fn embedded_origin_is_shell_quoted() {
        let s = super::script("https://hub.example/'test");
        assert!(s.contains("HUB='https://hub.example/'\\''test'"));
    }
}
