//! 安装脚本:Hub 提供,包含二进制下载与 systemd 安装。

/// 生成 install.sh 文本。`hub_base` 形如 `https://hub.example.com:9443`。
pub fn script(hub_base: &str) -> String {
    format!(
        r#"#!/bin/sh
# rooster agent installer (generated by the hub)
set -eu

HUB="{hub_base}"
TOKEN=""
ALLOW_UNSIGNED=0
INSECURE=0
NAME="$(hostname)"
BIN_DIR="/usr/local/bin"
CONF_DIR="/etc/rooster"
DATA_DIR="/var/lib/rooster"

while [ $# -gt 0 ]; do
  case "$1" in
    --hub) HUB="$2"; shift 2 ;;
    --token) TOKEN="$2"; shift 2 ;;
    --name) NAME="$2"; shift 2 ;;
    --allow-unsigned) ALLOW_UNSIGNED=1; shift ;;
    --insecure) INSECURE=1; shift ;;
    *) echo "unknown arg: $1" >&2; exit 1 ;;
  esac
done

[ -n "$TOKEN" ] || {{ echo "usage: install.sh --hub URL --token TOKEN [--name NAME] [--allow-unsigned] [--insecure]" >&2; exit 1; }}
command -v curl >/dev/null 2>&1 || {{ echo "curl is required" >&2; exit 1; }}

# --insecure: curl 下载不校验证书,仅用于自签证书的内网 hub。
CURL="curl -fsSL"
if [ "$INSECURE" = 1 ]; then
  CURL="curl -fsSLk"
fi

# 1) binary + signature. Prefer the signed release package for this
#    arch and verify it against the hub's configured Ed25519 public key. The
#    hub's own executable has no signature, so it is accepted only with an
#    explicit --allow-unsigned (same-arch dev installs) — never silently.
TMP_DIR="$(mktemp -d)"
ARCH="$(uname -m)"
if $CURL -o "$TMP_DIR/rooster.new" "$HUB/v0/downloads/rooster-$ARCH"; then
  SIGNED=1
elif $CURL -o "$TMP_DIR/rooster.new" "$HUB/v0/downloads/rooster"; then
  SIGNED=0
else
  echo "no rooster binary served by this hub: upload a signed package first" >&2
  exit 1
fi
if [ "$SIGNED" = 1 ]; then
  $CURL -o "$TMP_DIR/rooster.sig" "$HUB/v0/downloads/rooster-$ARCH.sig" || {{
    echo "package uploaded without a signature; refusing to install" >&2; exit 1; }}
  $CURL -o "$TMP_DIR/rooster.pub" "$HUB/v0/pubkey.pem" || {{
    echo "hub has no upgrade-public-key; cannot verify the package" >&2; exit 1; }}
  command -v openssl >/dev/null 2>&1 || {{
    echo "openssl is required to verify the package signature" >&2; exit 1; }}
  # openssl 3.x 的 `dgst -verify` 对 Ed25519 有 ~16MiB 单次输入限制,
  # 正式发布包(agent 链接 wasmtime)会超限;`pkeyutl -rawin` 吃同一
  # 裸 64 字节签名与 SPKI 公钥且没有该限制。stderr 原样透出失败原因。
  openssl pkeyutl -verify -pubin -inkey "$TMP_DIR/rooster.pub" -rawin \
    -in "$TMP_DIR/rooster.new" -sigfile "$TMP_DIR/rooster.sig" >/dev/null || {{
    echo "package signature verification FAILED" >&2; exit 1; }}
elif [ "$ALLOW_UNSIGNED" != 1 ]; then
  echo "only the hub's own unsigned binary is available; upload a signed package for $ARCH, or pass --allow-unsigned" >&2
  exit 1
fi
install -m 0755 "$TMP_DIR/rooster.new" "$BIN_DIR/rooster"
rm -rf "$TMP_DIR"

# 2) config with one-time registration token
mkdir -p "$CONF_DIR" "$DATA_DIR"

# --insecure 不只放宽下载:顺手按 TOFU 抓 hub 的服务器信任锚(/v0/ca.crt)
# 写进 Agent 的 hub.ca。装完后 Agent 仍做链+SAN 完整校验;拿不到锚
# (公 CA 或 hub 未配 tls.ca)就留空,由管理员自行放 ca 文件。
CA_FILE=""
if [ "$INSECURE" = 1 ]; then
  case "$HUB" in
    https://*)
      if $CURL -o "$CONF_DIR/server-ca.crt" "$HUB/v0/ca.crt"; then
        CA_FILE="$CONF_DIR/server-ca.crt"
      fi
      ;;
  esac
fi
CA_LINE=""
if [ -n "$CA_FILE" ]; then CA_LINE="    ca: $CA_FILE"; fi

SECRET="$(head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n')"
WS_URL="$(echo "$HUB" | sed 's|^https://|wss://|; s|^http://|ws://|')/agent/ws"
cat > "$CONF_DIR/config.yaml" <<EOF
local:
  agent:
    node-name: "$NAME"
    data-dir: $DATA_DIR
  management:
    listen: 127.0.0.1:9870
    secret-key: "$SECRET"
  hub:
    url: $WS_URL
    token: "$TOKEN"
$CA_LINE
EOF

# 3) systemd unit
cat > /etc/systemd/system/rooster.service <<'EOF'
[Unit]
Description=Rooster protection agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart={bin}/rooster agent --config {conf}/config.yaml
Restart=always
RestartSec=3
# 升级失败自恢复:启动前若更新标记存在且上次启动失败,回退 rooster.prev。
# upgrade-guard 是 agent 的子命令(clap: rooster agent upgrade-guard),
# 写错路径 systemd 会在 ExecStartPre 直接失败,agent 永远起不来。
ExecStartPre={bin}/rooster agent upgrade-guard --data-dir {data}

[Install]
WantedBy=multi-user.target
EOF
sed -i "s|{bin}/rooster|$BIN_DIR/rooster|; s|{conf}/config.yaml|$CONF_DIR/config.yaml|; s|{data}|$DATA_DIR|" /etc/systemd/system/rooster.service

systemctl daemon-reload
systemctl enable --now rooster
echo "rooster agent installed and started (node-name: $NAME)"
"#,
        hub_base = hub_base,
        bin = "{bin}",
        conf = "{conf}",
        data = "{data}",
    )
}

#[cfg(test)]
mod tests {
    #[test]
    fn insecure_download_executes_curl_with_separate_arguments() {
        let script = super::script("https://hub.example.com:9443");
        let downloads = script.split("install -m 0755").next().unwrap();
        // Fail both downloads before any privileged writes; exercise real shell parsing.
        let mock = "curl() { printf 'curl-arg=%s\\n' \"$@\"; return 1; }\nmktemp() { printf /unused; }\n";
        for insecure in [false, true] {
            let mut cmd = std::process::Command::new("sh");
            cmd.arg("-c").arg(format!("{mock}{downloads}"))
                .args(["install.sh", "--token", "test-token"]);
            if insecure {
                cmd.arg("--insecure");
            }
            let output = cmd.output().expect("run installer with mock curl");
            assert!(!output.status.success());
            let stdout = String::from_utf8(output.stdout).unwrap();
            let flag = if insecure { "-fsSLk" } else { "-fsSL" };
            assert_eq!(stdout.matches(&format!("curl-arg={flag}\n")).count(), 2,
                "both binary download attempts must execute curl: {}",
                String::from_utf8_lossy(&output.stderr));
        }
    }

    /// --insecure 必须把信任锚一路带到 Agent 配置里(rustls 只认
    /// webpki 根 ∩ hub.ca,自签 hub 没有这个锚就永远 UnknownIssuer)。
    /// 跑真实的 config 生成片段,验证只有 --insecure 才会落锚 + 写 hub.ca。
    #[test]
    fn insecure_installer_pins_the_hub_server_ca() {
        let script = super::script("https://hub.example.com:9443");
        let block = script
            .split("# 2) config with one-time registration token")
            .nth(1)
            .and_then(|s| s.split("# 3) systemd unit").next())
            .expect("config block is delimited by steps 2 and 3")
            .to_string();
        // 只吐个假 PEM:本测试只关心“拓没拓、写没写”,不验证证书内容。
        let mock = "curl() { while [ $# -gt 1 ]; do if [ \"$1\" = -o ]; then printf -- '-----BEGIN CERTIFICATE-----\\nMA==\\n-----END CERTIFICATE-----\\n' > \"$2\"; return 0; fi; shift; done; return 0; }\nCURL='curl -fsSL'\n";
        for insecure in [false, true] {
            let dir = std::env::temp_dir().join(format!(
                "rooster-ca-pin-{}-{}",
                std::process::id(),
                insecure as u8
            ));
            let _ = std::fs::remove_dir_all(&dir);
            std::fs::create_dir_all(&dir).unwrap();
            let prelude = format!(
                "CONF_DIR={d}\nDATA_DIR={d}/data\nHUB=https://hub.example.com:9443\nTOKEN=tk\nNAME=n\nINSECURE={i}\n",
                d = dir.display(),
                i = insecure as u8
            );
            let out = std::process::Command::new("sh")
                .arg("-c")
                .arg(format!("{mock}{prelude}{block}"))
                .output()
                .expect("run config block");
            assert!(
                out.status.success(),
                "config block failed: {}",
                String::from_utf8_lossy(&out.stderr)
            );
            let cfg = std::fs::read_to_string(dir.join("config.yaml")).unwrap();
            assert_eq!(
                cfg.contains("server-ca.crt"),
                insecure,
                "hub.ca 只能在 --insecure 时写入:\n{cfg}"
            );
            assert_eq!(
                dir.join("server-ca.crt").exists(),
                insecure,
                "信任锚文件必须与 hub.ca 配置同进同出"
            );
            let _ = std::fs::remove_dir_all(&dir);
        }
    }

    #[test]
    fn script_renders() {
        let s = super::script("https://hub.example.com:9443");
        assert!(s.contains("HUB=\"https://hub.example.com:9443\""));
        assert!(s.contains("rooster.service"));
        // 要求脚本自带签名校验,且必须用对 Ed25519 大输入也成立
        // 的 pkeyutl 形式(dgst 对 >16MiB 输入直接失败)。
        assert!(s.contains("v0/pubkey.pem"));
        assert!(
            s.contains("openssl pkeyutl -verify -pubin") && s.contains("-rawin") && s.contains("-sigfile"),
            "script must verify with the pkeyutl -rawin form"
        );
        assert!(!s.contains("openssl dgst -verify"));
        // --allow-unsigned 语义不变:无签名包仍必须显式开关才接受。
        assert!(s.contains("[ \"$ALLOW_UNSIGNED\" != 1 ]"));
        // --insecure:自签 hub 时 curl 全部下载走 -k。
        assert!(s.contains("CURL=\"curl -fsSLk\""));
    }

    /// 生成 unit 的 ExecStartPre 必须与真实 clap 命令路径一致
    /// (`rooster agent upgrade-guard`,子命令挂在 Agent 下)。
    #[test]
    fn unit_exec_start_pre_matches_real_cli_path() {
        let s = super::script("https://hub.example.com:9443");
        let line = s.lines().find(|l| l.starts_with("ExecStartPre=")).expect("unit has ExecStartPre");
        assert_eq!(
            line,
            "ExecStartPre={bin}/rooster agent upgrade-guard --data-dir {data}",
            "ExecStartPre must be `rooster agent upgrade-guard --data-dir` (the real subcommand)"
        );
    }

    /// 从生成脚本中原样抠出 openssl 验签命令执行(替换 TMP_DIR),防止
    /// 脚本与测试各自漂移:对 >16MiB 的 Ed25519 签名文件也必须验得
    /// 过、篡改必须验不过;openssl 缺席时优雅跳过。
    #[test]
    fn installer_verify_command_handles_oversize_ed25519_input() {
        use base64::Engine as _;
        use ed25519_dalek::Signer;
        use std::process::{Command, Stdio};

        let openssl_missing = Command::new("openssl")
            .arg("version")
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .map(|s| !s.success())
            .unwrap_or(true);
        if openssl_missing {
            eprintln!("skipping: openssl unavailable");
            return;
        }

        let sk = ed25519_dalek::SigningKey::generate(&mut rand::rng());
        let b64 = base64::engine::general_purpose::STANDARD;
        let dir = std::env::temp_dir().join(format!(
            "rooster-install-big-{}-{}",
            std::process::id(),
            now_millis()
        ));
        std::fs::create_dir_all(&dir).unwrap();
        // 17MiB:超出 openssl dgst 对 Ed25519 的 16MiB 单次输入限制,
        // 即正常发布包的量级。
        let data = vec![0x5au8; 17 * 1024 * 1024];
        std::fs::write(dir.join("rooster.new"), &data).unwrap();
        std::fs::write(dir.join("rooster.sig"), sk.sign(&data).to_bytes()).unwrap();
        let pem = crate::api::ed25519_spki_pem(&format!(
            "ed25519:{}",
            b64.encode(sk.verifying_key().to_bytes())
        ))
        .expect("spki pem");
        std::fs::write(dir.join("rooster.pub"), pem).unwrap();

        let script = super::script("https://hub.example.com:9443");
        let start = script.find("openssl pkeyutl").expect("script uses pkeyutl");
        let cmdline = script[start..]
            .split("||")
            .next()
            .unwrap()
            .replace("\\\n", " ")
            .replace('\n', " ");
        let run = || {
            Command::new("sh")
                .arg("-c")
                .arg(&cmdline)
                .env("TMP_DIR", &dir)
                .output()
                .expect("sh -c openssl")
        };
        let ok = run();
        assert!(
            ok.status.success(),
            "verify must accept a correctly signed 17MiB file: {}\n{}",
            String::from_utf8_lossy(&ok.stdout),
            String::from_utf8_lossy(&ok.stderr)
        );

        let mut tampered = data;
        tampered[0] ^= 0xff;
        std::fs::write(dir.join("rooster.new"), &tampered).unwrap();
        let bad = run();
        assert!(!bad.status.success(), "verify must reject a modified binary");
        assert!(
            !bad.stderr.is_empty(),
            "failure must surface the openssl reason, not swallow stderr"
        );
        let _ = std::fs::remove_dir_all(&dir);
    }

    fn now_millis() -> u128 {
        std::time::SystemTime::now()
            .duration_since(std::time::UNIX_EPOCH)
            .map(|d| d.as_millis())
            .unwrap_or(0)
    }

    /// 生成的是给人 `curl | sh` 执行的脚本:语法错误等于安装链路全断,
    /// 所以直接拿 `sh -n` 当守门人。
    #[test]
    fn generated_script_is_valid_posix_sh() {
        use std::process::{Command, Stdio};
        let file = std::env::temp_dir().join(format!(
            "rooster-install-sh-{}.sh",
            std::process::id()
        ));
        std::fs::write(&file, super::script("https://hub.example.com:9443")).unwrap();
        let status = Command::new("sh")
            .arg("-n")
            .arg(&file)
            .stdout(Stdio::null())
            .stderr(Stdio::null())
            .status()
            .expect("sh must be available on the target platform");
        let _ = std::fs::remove_file(&file);
        assert!(status.success(), "generated install.sh is not valid POSIX sh");
    }
}
