//! 安装脚本:Hub 提供,包含二进制下载与 systemd 安装。

/// `hub_base` is a validated public HTTP(S) origin.
pub fn script(hub_base: &str) -> String {
    r#"#!/bin/sh
# rooster agent installer (generated by the hub)
set -eu
umask 077
HUB='{hub_base}'
TOKEN="" NAME="$(hostname)" CA_FILE="" ALLOW_UNSIGNED=0
BIN_DIR="${ROOSTER_BIN_DIR:-/usr/local/bin}"
CONF_DIR="${ROOSTER_CONF_DIR:-/etc/rooster}"
DATA_DIR="${ROOSTER_DATA_DIR:-/var/lib/rooster}"
UNIT_DIR="${ROOSTER_UNIT_DIR:-/etc/systemd/system}"
fail() { echo "error: $*" >&2; exit 1; }
while [ "$#" -gt 0 ]; do
  case "$1" in
    --hub|--token|--name|--ca-file)
      [ "$#" -ge 2 ] && [ -n "$2" ] || fail "missing value for $1"
      case "$1" in --hub) HUB="$2";; --token) TOKEN="$2";; --name) NAME="$2";; --ca-file) CA_FILE="$2";; esac
      shift 2;;
    --allow-unsigned) ALLOW_UNSIGNED=1; shift;;
    --insecure) fail "use the trusted enroll.sh with --ca-sha256, or provide --ca-file; unauthenticated downloads are refused";;
    *) fail "unknown argument: $1";;
  esac
done
[ "$(id -u)" = 0 ] || fail "run as root"
[ -n "$TOKEN" ] || fail "--token is required"
case "$NAME" in ''|*[!a-zA-Z0-9._-]*) fail "invalid node name";; esac
[ "${#NAME}" -le 64 ] || fail "node name exceeds 64 characters"
case "$HUB" in https://*) PROTO='=https';; http://localhost:*|http://127.0.0.1:*|http://\[::1\]:*) PROTO='=http';; *) fail "HTTPS is required outside loopback";; esac
case "$HUB" in *[!a-zA-Z0-9.:/\[\]_-]*) fail "invalid hub URL";; esac
HUB="${HUB%/}"
for cmd in curl openssl systemctl install; do command -v "$cmd" >/dev/null 2>&1 || fail "$cmd is required"; done
[ -z "$CA_FILE" ] || [ -f "$CA_FILE" ] || fail "CA file not found"
WS_URL="$(printf '%s' "$HUB" | sed 's|^https://|wss://|; s|^http://|ws://|')/agent/ws"
# Reinstall may replace configuration, but existing client identities cannot migrate silently.
if [ -f "$DATA_DIR/pki/agent.crt" ]; then
  [ -f "$CONF_DIR/config.yaml" ] || fail "existing PKI without config; restore its config before reinstalling"
  OLD_URL="$(sed -n 's/^[[:space:]]*url:[[:space:]]*//p' "$CONF_DIR/config.yaml" | tr -d "\"'")"
  OLD_NAME="$(sed -n 's/^[[:space:]]*node-name:[[:space:]]*//p' "$CONF_DIR/config.yaml" | tr -d "\"'")"
  [ "$OLD_URL" = "$WS_URL" ] && [ "$OLD_NAME" = "$NAME" ] || fail "existing PKI belongs to a different hub/name; back up and migrate identity explicitly"
fi
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT
trap 'exit 1' HUP INT TERM
fetch() {
  if [ -n "$CA_FILE" ]; then
    curl -fsSL --proto "$PROTO" --proto-redir "$PROTO" --connect-timeout 10 --max-time 120 --cacert "$CA_FILE" "$@"
  else
    curl -fsSL --proto "$PROTO" --proto-redir "$PROTO" --connect-timeout 10 --max-time 120 "$@"
  fi
}
# 1) verify all downloads before touching the installed files.
ARCH="$(uname -m)"
if fetch -o "$TMP_DIR/rooster.new" "$HUB/v0/downloads/rooster-$ARCH"; then
  SIGNED=1
elif fetch -o "$TMP_DIR/rooster.new" "$HUB/v0/downloads/rooster"; then
  SIGNED=0
else
  fail "no binary available; upload a signed release for $ARCH in the panel"
fi
if [ "$SIGNED" = 1 ]; then
  fetch -o "$TMP_DIR/rooster.sig" "$HUB/v0/downloads/rooster-$ARCH.sig" || fail "package has no signature"
  fetch -o "$TMP_DIR/rooster.pub" "$HUB/v0/pubkey.pem" || fail "configure upgrade-public-key in hub.yaml, restart the hub, and upload a signed release"
  # Ed25519 large files require pkeyutl -rawin, not dgst -verify.
  openssl pkeyutl -verify -pubin -inkey "$TMP_DIR/rooster.pub" -rawin \
    -in "$TMP_DIR/rooster.new" -sigfile "$TMP_DIR/rooster.sig" >/dev/null || fail "package signature verification FAILED"
elif [ "$ALLOW_UNSIGNED" != 1 ]; then
  fail "configure upgrade-public-key in hub.yaml, restart the hub and upload a signed package for $ARCH; --allow-unsigned is only for explicit same-arch development installs"
fi
chmod 700 "$TMP_DIR/rooster.new"
"$TMP_DIR/rooster.new" --version >/dev/null 2>&1 || fail "binary is incompatible with this host"
"$TMP_DIR/rooster.new" agent upgrade-guard --help >/dev/null 2>&1 || fail "binary does not support the systemd upgrade guard"

# 2) back up overwritten artifacts; never delete node data or PKI.
mkdir -p "$BIN_DIR" "$CONF_DIR" "$DATA_DIR" "$UNIT_DIR"
BACKUP="$(mktemp -d "$CONF_DIR/install-backup.XXXXXXXX")"
for file in "$CONF_DIR/config.yaml" "$CONF_DIR/server-ca.crt" "$BIN_DIR/rooster" "$UNIT_DIR/rooster.service"; do
  [ ! -e "$file" ] || cp -p "$file" "$BACKUP/"
done
quote_yaml() { printf "'"; printf '%s' "$1" | sed "s/'/''/g"; printf "'"; }
SECRET="$(openssl rand -hex 32)"
if [ -n "$CA_FILE" ]; then
  install -m 600 "$CA_FILE" "$CONF_DIR/.server-ca.new"
  mv -f "$CONF_DIR/.server-ca.new" "$CONF_DIR/server-ca.crt"
fi
{
  printf 'local:\n  agent:\n    node-name: '; quote_yaml "$NAME"
  printf '\n    data-dir: '; quote_yaml "$DATA_DIR"
  printf '\n  management:\n    listen: 127.0.0.1:9870\n    secret-key: '; quote_yaml "$SECRET"
  printf '\n  hub:\n    url: '; quote_yaml "$WS_URL"
  printf '\n    token: '; quote_yaml "$TOKEN"
  if [ -n "$CA_FILE" ]; then printf '\n    ca: '; quote_yaml "$CONF_DIR/server-ca.crt"; fi
  printf '\n'
} > "$CONF_DIR/.config.yaml.new"
chmod 600 "$CONF_DIR/.config.yaml.new"
mv -f "$CONF_DIR/.config.yaml.new" "$CONF_DIR/config.yaml"
install -m 755 "$TMP_DIR/rooster.new" "$BIN_DIR/.rooster.new"
mv -f "$BIN_DIR/.rooster.new" "$BIN_DIR/rooster"

cat > "$TMP_DIR/rooster.service" <<EOF
[Unit]
Description=Rooster protection agent
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
ExecStart=$BIN_DIR/rooster agent --config $CONF_DIR/config.yaml
Restart=always
RestartSec=3
ExecStartPre=$BIN_DIR/rooster agent upgrade-guard --data-dir $DATA_DIR

[Install]
WantedBy=multi-user.target
EOF
install -m 644 "$TMP_DIR/rooster.service" "$UNIT_DIR/rooster.service"
systemctl daemon-reload
systemctl enable rooster
systemctl restart rooster

# A live local API alone does not prove registration or the control channel is ready.
i=0
while [ "$i" -lt 60 ]; do
  if systemctl is-active --quiet rooster && \
    [ "$(curl -fsS --noproxy '*' --connect-timeout 1 --max-time 2 -H "Authorization: Bearer $SECRET" http://127.0.0.1:9870/v0/management/readyz 2>/dev/null || true)" = ok ]; then
    echo "rooster agent installed and connected (node-name: $NAME); overwritten files backed up in $BACKUP"
    exit 0
  fi
  i=$((i + 1))
  sleep 1
done
fail "agent did not connect to the hub; inspect journalctl -u rooster -n 50; backups: $BACKUP"
"#
    .replace("{hub_base}", &hub_base.replace('\'', "'\\''"))
}

#[cfg(test)]
mod tests {
    #[test]
    fn generated_script_is_valid_posix_sh() {
        use std::io::Write;
        use std::process::{Command, Stdio};
        let mut child = Command::new("sh").arg("-n").stdin(Stdio::piped()).spawn().unwrap();
        child.stdin.take().unwrap().write_all(super::script("https://hub.example:9443").as_bytes()).unwrap();
        assert!(child.wait().unwrap().success());
    }

    #[test]
    fn script_enforces_verified_downloads_and_readiness() {
        let s = super::script("https://hub.example:9443");
        assert!(s.contains("--cacert"));
        assert!(!s.contains("curl -fsSLk"));
        assert!(s.contains("openssl pkeyutl -verify -pubin") && s.contains("-rawin"));
        assert!(s.contains("[ \"$ALLOW_UNSIGNED\" != 1 ]"));
        assert!(s.contains("systemctl restart rooster"));
        assert!(s.contains("/v0/management/readyz"));
    }

    #[test]
    fn embedded_origin_is_shell_quoted() {
        let s = super::script("https://hub.example/'test");
        assert!(s.contains("HUB='https://hub.example/'\\''test'"));
    }
}
