//! 构建期把仓库内置 CRS 规则子集(`../../rules/crs`)嵌入 agent 二进制。
//!
//! 动机:CRS 依赖规则文件在节点本地存在,而节点侧没有任何分发通道
//! (hub 只分发二进制与 WASM 插件),结果 `waf.crs.enabled: true` 在无外部分发的
//! 节点上静默降级成"只加载内置签名"。内嵌后 CRS 在任意节点都可用;
//! `rules/` 仍是唯一来源,升级规则集 = 发版(签名升级通道已有)。
//!
//! 生成物:`$OUT_DIR/crs_embedded.rs` → `CRS_FILES: &[(&str, &[u8])]` 与
//! `CRS_FINGERPRINT`(文件名+内容的 FNV-1a 64 位哈希,用于运行期判断
//! 已落盘的副本是否属于当前构建)。

use std::env;
use std::fs;
use std::path::PathBuf;

/// 与运行期加载口径一致:收 `.conf`(排除 `.conf.example`)与 `.data`。
fn wanted(name: &str) -> bool {
    (name.ends_with(".conf") && !name.ends_with(".conf.example")) || name.ends_with(".data")
}

fn fnv1a(hash: &mut u64, bytes: &[u8]) {
    for b in bytes {
        *hash ^= *b as u64;
        *hash = hash.wrapping_mul(0x0100_0000_01b3);
    }
}

fn main() {
    let manifest = PathBuf::from(env::var("CARGO_MANIFEST_DIR").expect("manifest dir"));
    let rules_dir = manifest.join("../../rules/crs");
    println!("cargo:rerun-if-changed={}", rules_dir.display());

    let mut entries: Vec<(String, PathBuf)> = match fs::read_dir(&rules_dir) {
        Ok(rd) => rd
            .filter_map(|e| e.ok())
            .map(|e| {
                let p = e.path();
                let name = p.file_name().unwrap_or_default().to_string_lossy().to_string();
                (name, p)
            })
            .filter(|(name, _)| wanted(name))
            .collect(),
        Err(e) => panic!("cannot read builtin CRS rules at {}: {e}", rules_dir.display()),
    };
    entries.sort_by(|a, b| a.0.cmp(&b.0));
    if entries.is_empty() {
        panic!("no CRS rule files found in {}", rules_dir.display());
    }

    let out_dir = PathBuf::from(env::var("OUT_DIR").expect("out dir"));
    let mut hash: u64 = 0xcbf2_9ce4_8422_2325;
    let mut body = String::from(
        "// @generated by build.rs — do not edit. 内置 CRS 规则子集的编译期副本。\n\
         pub const CRS_FILES: &[(&str, &[u8])] = &[\n",
    );
    for (name, path) in &entries {
        let bytes = fs::read(path).unwrap_or_else(|e| panic!("read {}: {e}", path.display()));
        fnv1a(&mut hash, name.as_bytes());
        fnv1a(&mut hash, &bytes);
        body.push_str(&format!(
            "    ({:?}, include_bytes!({:?})),\n",
            name,
            path.canonicalize().unwrap_or_else(|_| path.clone())
        ));
    }
    body.push_str("];\n");
    body.push_str(&format!("pub const CRS_FINGERPRINT: &str = \"{:016x}\";\n", hash));
    body.push_str(&format!("pub const CRS_FILE_COUNT: usize = {};\n", entries.len()));

    fs::write(out_dir.join("crs_embedded.rs"), body).expect("write crs_embedded.rs");
}
