[package]
name = "rooster-agent"
version.workspace = true
edition.workspace = true
publish.workspace = true

[dependencies]
rooster-config.workspace = true
rooster-nft.workspace = true
rooster-proto.workspace = true
rooster-waf.workspace = true
axum.workspace = true
base64.workspace = true
bcrypt.workspace = true
bytes.workspace = true
ed25519-dalek.workspace = true
flate2.workspace = true
futures-util.workspace = true
hickory-resolver.workspace = true
http.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-util.workspace = true
instant-acme.workspace = true
ipnet.workspace = true
libc.workspace = true
maxminddb.workspace = true
rand.workspace = true
rcgen.workspace = true
regex.workspace = true
reqwest.workspace = true
rmp-serde.workspace = true
redb.workspace = true
rustls.workspace = true
rustls-pemfile.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_norway.workspace = true
tokio.workspace = true
tokio-rustls.workspace = true
tokio-tungstenite.workspace = true
tower.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
wasmtime.workspace = true
webpki-roots.workspace = true

[dev-dependencies]
